--- # my first Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: firstdeploy
  labels:
    name: firstdeploy     
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: dpod
      labels:
        app: myapp
    spec:
      containers:
        - name: container
          image: coolgourav147/nginx-custom

