--- # this is for resource limit

kind: ResourceQuota
apiVersion: v1
metadata:
  name: myquota
spec:
  hard:
    pods: 10
    requests.cpu: 0.5
    requests.memory: 100Mi
    limits.cpu: 1
    limits.memory: 1Gi
